// src/components/intro-banner.vue
<template>
  <div class="flex justify-center">
    <div class="dark:text-white text-outer-space px-6 lg:grid lg:grid-cols-3 lg:max-w-[930px]">
      <div class="lg:col-span-2">
        <h2
          class="md:text-[112px] leading-none text-[56px] mt-4 font-semibold text-border text-shadow"
        >
          Software Engineer based in Central Java, Indonesia.
        </h2>
      </div>
      <div class="flex flex-col lg:justify-end lg:items-end">
        <h3 class="leading-none mt-4 font-semibold">Erick Hilda Andreas</h3>
        <div class="my-3 flex md:flex-row flex-col">
          <a href="https://www.linkedin.com/in/erickhilda/" target="_blank"> Linkedin </a>
          <span class="mx-2 hidden md:block">•</span>
          <a href="https://github.com/erickhilda" target="_blank"> Github </a>
          <span class="mx-2 hidden md:block">•</span>
          <a href="https://twitter.com/erickhlda" target="_blank"> Twitter </a>
        </div>
      </div>
    </div>
  </div>
</template>

// src/components/home/intro-banner.tsx
import clsx from "clsx"
import Link from "next/link"

function IntorBanner() {
  return (
    <div className='flex justify-center'>
      <div className='dark:text-white text-outer-space px-6 lg:grid lg:grid-cols-3 lg:max-w-[930px]'>
        <div className='lg:col-span-2'>
          <h2 className={clsx(
            'md:text-[112px] leading-none text-[56px] mt-4 font-semibold',
            'text-border text-shadow'
          )}>
            Software Engineer based in Central Java, Indonesia.
          </h2>
        </div>
        <div className='flex flex-col lg:justify-end lg:items-end'>
          <h3 className='leading-none mt-4 font-semibold'>
            Erick Hilda Andreas
          </h3>
          <div className='my-3 flex md:flex-row flex-col'>
            <Link href='https://www.linkedin.com/in/erickhilda/'>
              <a>Linkedin</a>
            </Link>
            <span className='mx-2 hidden md:block'>•</span>
            <Link href='https://github.com/erickhilda'>
              <a>Github</a>
            </Link>
            <span className='mx-2 hidden md:block'>•</span>
            <Link href='https://twitter.com/hiii_erick'>
              <a>Twitter</a>
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}

export default IntorBanner
